### PR TITLE
Trying to fix crash at startup

### PR DESCRIPTION
**Pull request by rooi**

### CODE REVIEW

**Comment by brownad** [comment]
nice :+1:

**Comment by luc-ass** [comment]
Did you manage to get things working with temperature below 10 °C?

**Comment by brownad** [comment]
You sure this works for you below 10 °C?

**Comment by rooi** [comment]
I just tried to fix the crash at startup. I just checked and temp < 10 does not seem to work. Homekit's thermostat does not seem to respond to any min max or step settings.

I also tried the following, but no luck (even when setting minTemp to 15):

        this.thermostatService.getCharacteristic(Characteristic.CurrentTemperature)
        .setProps({
                  minValue: this.minTemp,
                  maxValue: this.maxTemp,
                  minStep: 0.5
                  });

  		// this.addCharacteristic(Characteristic.TargetTemperature); READ WRITE
  		this.thermostatService
  			.getCharacteristic(Characteristic.TargetTemperature)
  			.on('get', this.getTargetTemperature.bind(this))
  			.on('set', this.setTargetTemperature.bind(this));
	    
        this.thermostatService.getCharacteristic(Characteristic.TargetTemperature)
        .setProps({
                  minValue: this.minTemp,
                  maxValue: this.maxTemp,
                  minStep: 0.5
                  });

**Comment by brownad** [comment]
Cool, thought I was the only one :|

**Pull request merged**
