### PR TITLE
Resolved change temperature until next scheduled event (+ new API to manage this)

### PR DESCRIPTION
**Pull request by fredericvl**
Resolved change temperature until next scheduled event (+ new API to manage this)
Also resolved issue #19 with an configurable interval to set the temperature.

### CODE REVIEW

**Comment by luc-ass** [comment]
perfect, thanks!

**Comment by luc-ass** [comment]
Hey, I have another question. My heating system doesn't seem to read the correct nextTime value. It always sets the new temperature until 00:00:00. Any Ideas on what's wrong?

**Comment by fredericvl** [comment]
Hi, is this related to #23 you've created or?
For me it seems to be working but my raspberry pi with homebridge running on it is configured in CET (local time as I live in Belgium).
I think homebridge needs to have the timezone where you are living.

**Comment by luc-ass** [comment]
Hm, I moved my homebridge into a Docker container on my Synology DS. Can't figure out how to change the system time inside the container...

**Comment by fredericvl** [comment]
I'll try to change the code so it manipulates the timezone.
I see I can get the correct timezone from Honeywell:

`            "timeZone": {`
`                "timeZoneId": "RomanceStandardTime",`
`                "displayName": "(UTC+01:00) Brussel, Kopenhagen, Madrid, Parijs",`
`                "offsetMinutes": 60,`
`                "currentOffsetMinutes": 60,`
`                "supportsDaylightSaving": true`
`            },`

**Comment by luc-ass** [comment]
Strange. I was able to set the system time of the Docker container to Europe/Berlin. `date` and homebridge log now show the right time. Still everything changes to 00:00:00.

**Comment by fredericvl** [comment]
Do you have another change in the schedule for that zone today?
Let's say if the following schedule change is tomorrow at 06:00 then it will change the time until 00:00 and not until 06:00 next day. It only checks he same day.

**Comment by luc-ass** [comment]
Yes, I have tried it with all my zones and at least three of them have schedule changes today. It is not a huge problem (I mean it is already pretty awesome!) - just wanted to let you know.

**Comment by fredericvl** [comment]
I've created a new pull request #24 where timezone support is in.
Also I've added extra logging so you can see what schedule points it has for today when you set a new target temperature, maybe we can troubleshoot further your problem with that logging.

**Comment by luc-ass** [comment]
great work, thanks. I'll give it a shot.

**Comment by plangin** [comment]
Hey,
is it possible to change the behavior here? Means, change the temperature until the next schedule event next day? instead of 00:00

Example: I go to bed before midnight and want to raise temperature 1° until next morning. Next scheduled event is 8:00 AM.

So right now, I can only influence the temperature until midnight. For a change until 8:00 AM, I still need to use Honeywell's app

Is this possible? Thanks.

**Pull request merged**
