### PR TITLE
fix #61 do not return empty array of accessories

### LINKED ISSUE #61: Evohome devices randomly reset in My Home UI
I have been successfully using this plugin with homekit for a while now. Great work on creating this fantastic plugin. However, over the last few months, usually triggered by a reboot of my homebridge, Apple Home forgets all room allocations and updated names of my evohome items - thermostats and evohome mode switches - everything ends up in their default settings, and also dropps out of scenes. It is almost like (and I assume here) that homebridge is forgetting/not caching the old device ids, and issuing new ones which are effectively new to Apple Home, and it treats them as new devices.

I am on the latest version of everything, and am running on Raspberry Pi platform.

Is anyone else struggling with this problem? Is there a resolution through configuration? Or is this a bug?

Thanks for your help,

Chris

### PR DESCRIPTION
**Pull request by coolweb**

### CODE REVIEW

**Comment by luc-ass** [comment]
Thank you for your PR! It's awesome to see some work on this. 🚀

Have you tested this? What happens when the login fails but the server returns after a few minutes? Could you elaborate a little?

I remember adding those callbacks to make the Plug-in non-blocking. Must be a few years ago...

**Comment by coolweb** [comment]
I didn't test it, but if the plugin is not confiugred as a child bridge it'll block homebridge, but as a child bridge it'll not block homebridge. This is the remark of  @ebaauw.

**Comment by luc-ass** [comment]
Got it. The empty callback was needed to make the plugin non-blocking. This was proposed by the homebridge-team to have the plugin verified.

I'll do the following:
- [ ] Test your PR against server failure/recovery to see whether it returns to normal by itself
- [ ] Add a LARGE warning, that this plugin may only be run as a child bridge to prevent blocking
- [ ] Research whether we could return an error instead of an empty array

I'll let you know how it goes. Thanks again! 👏

**Comment by MonsterArtur1** [comment]
There are other plugins, like WIZ bulb that didn't block homeridge and also shows devices as offline when unavailable.
Maybe there is a hint? Maybe we need to cache accessory id when unavailable? 
Sorry for being not helpful with code :(

**Comment by luc-ass** [comment]
@MonsterArtur1 No worries. Every part of the discussion helps. 👍 The WIZ-Plugin was written according to the new Typescript guidelines. This automatically deals with the problem. It's just that I am missing the resources to rewrite the plugin at the moment. 🥲

@coolweb I verified that changing `callback([])` to `callback()` (without empty array) preserves the aid/iid of the accessories, but still removes them from HomeKit. They reappear after adding the correct credentials, but I couldn't see whether this still breaks automations... testing... 🧪 

I have contacted donavanbecker in the original [issue](https://github.com/homebridge/verified/issues/63), let's see if he has some input 💡

**Comment by coolweb** [comment]
@luc-ass after some research, it appears that the plugin should start after the event **didFinishLaunching**, in the doc: 
   ```
      api.on('didFinishLaunching', () => {
      const uuid = api.hap.uuid.generate('SOMETHING UNIQUE');
      
      // check the accessory was not restored from cache
      if (!this.accessories.find(accessory => accessory.UUID === uuid)) {
        // create a new accessory
        const accessory = new this.api.platformAccessory('DISPLAY NAME', uuid);
        // register the accessory
        api.registerPlatformAccessories('PLUGIN_NAME', 'PLATFORM_NAME', [accessory]);
      }
    });```

**Comment by luc-ass** [comment]
That's for "dynamic platforms" (loading accessories _after_ homebridge started). This plugin is a static platform. It loads the accessories at runtime. One more thing that would be solved by a rewrite 😆

Never the less this is a good example on how to read/load accessories from cache. Testing... 🧪

**Comment by luc-ass** [comment]
Just a quick follow up, your pull request has not been forgotten. I'll include this in a future version, but I will probably include a switch to turn this off.

**Comment by luc-ass** [comment]
I am merging this into "persistent-accessories" and test it. Keep an eye on it. 😉

**Pull request merged**
