### PR TITLE
Periodic update modified to update value on current temp and target t…

### PR DESCRIPTION
**Pull request by slippyr4**
18e4f27 "Remove unnecessary set characteristics on periodic update" removed some characteristic setValue from periodic update which was incorrect, and causes displayed values to invariably be wrong in the Home app, since Home caches values (as does Homebridge).

This adds the necessary updates to current temp, set temp and current/target state so that the information in the Home app is correct, and updates at the frequency set for the periodic update.

Also the logic for Characteristic.CurrentHeatingCoolingState get was wrong; that should show what the heating is actually doing right now - which is in effect, whether there is call for heat. With the previous logic which was duplicating Characteristic.TargetHeatingCoolingState, all zones showed as actively heating in the Home app, even when they had no call for heat.

### CODE REVIEW

**Comment by luc-ass** [comment]
thank you very much! Has it been stable for you so far?

**Comment by slippyr4** [comment]
Yes, I’ve had no problems. I’ve been running it since creating this PR

**Comment by slippyr4** [comment]
Also I believe this resolves #41

**Comment by luc-ass** [comment]
I’ll have al look at it on the weekend. Thanks again!

**Comment by luc-ass** [comment]
are any changes to the config needed?

**Comment by slippyr4** [comment]
No, none

**Comment by luc-ass** [comment]
it has now been merged and published to NPM.

**Pull request merged**
