### PR TITLE
Fix for next schedule time (make sure time is 24h format)

### PR DESCRIPTION
**Pull request by fredericvl**
Fix for next schedule time (make sure time is 24h format)

### CODE REVIEW

**Comment by luc-ass** [comment]
no luck. same problem persists.

**Comment by luc-ass** [comment]
but my locale ist still AM/PM
let me check wether i can change that.

**Comment by luc-ass** [comment]
no luck. The container is already running in a 24 hour format. It is only homebridge running in AM/PM. Any ideas on how to change that?

**Comment by luc-ass** [comment]
bildschirmfoto 2018-01-20 um 21 10 55

I added additional logging and found out that you are right. It seems to be the AM/PM-Problem.

**Comment by luc-ass** [comment]
ha! I made it work. Your idea was right, just needed to generate the right locale. The line is now set to de-DE as well as timeZone Europe/Berlin and hour12: false

**Comment by fredericvl** [comment]
Nice, good work!

**Comment by luc-ass** [comment]
Bumped version. Published on NPM (0.2.2.). Thanks again for all your hard work!

**Pull request merged**
